#ifndef QTWIDGETPLUGIN_GLOBAL_H
#define QTWIDGETPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTWIDGETPLUGIN_LIBRARY)
#  define QTWIDGETPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTWIDGETPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QTWIDGETPLUGIN_GLOBAL_H
